version: '3.3'

services:
  web:
    build: ./app
    container_name: application
    restart: always
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - ./.docker.dev.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres14_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.docker.dev.env
    environment:
      - POSTGRES_USER=ms
      - POSTGRES_PASSWORD=ms
      - POSTGRES_DB=ms
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    env_file:
      - ./.docker.dev.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ms@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ms
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static:/var/www/html/static
      - media:/var/www/html/media
    depends_on:
      - web

volumes:
  postgres_data:
  pgadmin_data:
  static:
  media: