# Generated by Django 4.2.7 on 2023-12-02 11:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30)])),
                ('name', models.CharField(unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(5)])),
                ('need_recipe', models.BooleanField(verbose_name='Нужен ли рецепт?')),
                ('number_of_tablets', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество таблеток')),
                ('dosage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дозировка')),
            ],
            options={
                'verbose_name': 'Лекартсвенный препарат',
                'verbose_name_plural': 'Лекартсвенные препараты',
            },
        ),
    ]
