# Generated by Django 4.2.7 on 2023-12-02 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyMedicinalDrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='Цена в рублях')),
                ('medicinal_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.medicine', verbose_name='Лекартственный препарат')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Цена на лакарство в аптеке',
                'verbose_name_plural': 'Цены на лакарства в аптеках',
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacymedicinaldrugprice',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicinal_drug'), name='pharmacy_medicinal_drug'),
        ),
    ]
